/*
Script generated by Aqua Data Studio 16.0.5-9 on Aug-19-2016 02:44:34 PM
Database: hs
Schema: <All Schemas>
Objects: TABLE, VIEW, PROCEDURE, FUNCTION, TRIGGER, EVENT
*/
DROP TABLE IF EXISTS "timer"
GO

DROP TABLE IF EXISTS "sms_outbox"
GO

DROP TABLE IF EXISTS "sms_inbox"
GO

DROP TABLE IF EXISTS "sensors_data"
GO

DROP TABLE IF EXISTS "parameters"
GO

DROP TABLE IF EXISTS "logs"
GO


CREATE TABLE "logs"  ( 
	"id"         	int(11) AUTO_INCREMENT NOT NULL,
	"module_name"	varchar(255) NOT NULL,
	"dated"      	datetime NOT NULL,
	"level"      	varchar(10) NOT NULL,
	"message"    	varchar(1000) NOT NULL,
	PRIMARY KEY("id")
)
ENGINE = InnoDB
CHARACTER SET latin1
COLLATE latin1_swedish_ci
AUTO_INCREMENT = 6386
GO

CREATE TABLE "parameters"  ( 
	"id"            	int(11) AUTO_INCREMENT NOT NULL,
	"name"          	varchar(25) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
	"alias"         	varchar(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
	"description"   	varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
	"format_pattern"	varchar(25) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
	"unit"          	varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
	"type"          	varchar(25) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
	PRIMARY KEY("id")
)
ENGINE = InnoDB
AUTO_INCREMENT = 10
GO

CREATE TABLE "sensors_data"  ( 
	"rec_id"        	int(11) AUTO_INCREMENT NOT NULL,
	"parameter_id"  	int(11) NOT NULL,
	"date"          	datetime NOT NULL,
	"value_d"       	double NULL,
	"value_s"       	varchar(255) NULL,
	"value_b"       	int(11) NULL,
	"value_i"       	int(11) NULL,
	"value_min"     	double NULL,
	"date_min"      	datetime NULL,
	"value_max"     	double NULL,
	"date_max"      	datetime NULL,
	"transfer_count"	int(11) NULL,
	PRIMARY KEY("rec_id")
)
ENGINE = InnoDB
AUTO_INCREMENT = 38
GO

CREATE TABLE "sms_inbox"  ( 
	"id"     	int(11) AUTO_INCREMENT NOT NULL,
	"message"	varchar(140) NOT NULL,
	"sender" 	varchar(25) NOT NULL,
	"date"   	datetime NOT NULL,
	"status" 	int(11) NOT NULL,
	PRIMARY KEY("id")
)
ENGINE = InnoDB
CHARACTER SET latin1
COLLATE latin1_swedish_ci
AUTO_INCREMENT = 1
GO

CREATE TABLE "sms_outbox"  ( 
	"id"       	int(11) AUTO_INCREMENT NOT NULL,
	"message"  	varchar(70) NOT NULL,
	"recipient"	varchar(25) NOT NULL,
	"date"     	datetime NOT NULL,
	"status"   	int(11) NOT NULL,
	PRIMARY KEY("id")
)
ENGINE = InnoDB
CHARACTER SET latin1
COLLATE latin1_swedish_ci
AUTO_INCREMENT = 1
GO

CREATE TABLE "timer"  ( 
	"id"        	int(11) AUTO_INCREMENT NOT NULL,
	"name"      	varchar(100) NOT NULL,
	"start_date"	datetime NULL,
	"period"    	int(11) NULL,
	"enabled"   	int(11) NOT NULL,
	PRIMARY KEY("id")
)
ENGINE = InnoDB
CHARACTER SET latin1
COLLATE latin1_swedish_ci
AUTO_INCREMENT = 4
GO


INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(1, 'Internal Temperature', 'INTERNAL_TEMP', 'temperature on inetrnal sensor', NULL, '°C', 'DOUBLE')
GO
INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(2, 'Internal Humidity', 'INTERNAL_HUMIDITY', NULL, NULL, '%', 'DOUBLE')
GO
INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(3, 'Lumiosity', 'LUMIOSITY', NULL, NULL, 'lx', 'DOUBLE')
GO
INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(4, 'Battery Voltage', 'VBAT_SENSOR', NULL, NULL, 'V', 'DOUBLE')
GO
INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(5, 'AC Voltage', 'VAC_SENSOR', NULL, NULL, 'V', 'DOUBLE')
GO
INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(6, 'PIR Sensor', 'PIR_SENSOR', NULL, NULL, NULL, 'BOOLEAN')
GO
INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(7, 'Gas Sensor', 'GAS_SENSOR', NULL, NULL, NULL, 'BOOLEAN')
GO
INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(8, 'Gas Sensor Signal', 'GAS_SENSOR_ANALOG', NULL, NULL, 'V', 'DOUBLE')
GO
INSERT INTO "parameters"("id", "name", "alias", "description", "format_pattern", "unit", "type")
  VALUES(9, 'Battery Temperature', 'BATT_TEMP', NULL, NULL, '°C', 'DOUBLE')
GO
INSERT INTO "timer"("id", "name", "start_date", "period", "enabled")
  VALUES(1, 'internal_sensors_poll', NULL, 10, 1)
GO
INSERT INTO "timer"("id", "name", "start_date", "period", "enabled")
  VALUES(2, 'write_db_data', NULL, 300, 1)
GO
INSERT INTO "timer"("id", "name", "start_date", "period", "enabled")
  VALUES(3, 'db_clearing', '2014-01-05 01:00:00.0', 86400, 1)
GO
