/*
Script generated by Aqua Data Studio 16.0.5-9 on Aug-19-2016 02:43:13 PM
Objects: DATABASE, USER
*/
DROP DATABASE "hs"
GO

CREATE DATABASE "hs"
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci
GO

